server:
  port: 8083

spring:
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        server-addr: 101.42.160.59:8848/
        service: ${spring.application.name}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.42.160.59:3306/cloud_alibaba?useUnicode=true&useSSL=false&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: ywl123000...

mybatis-plus:
  mapper-locations: "classpath:com.yao.product.mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl